import React from "react";
import "./Homeblog.scss";

const Homeblog = () => {
  return (
    <div className="blog_container">
      <div className="blog_item">
        <p className="blog_title">The AI Block</p>
        <p className="blog_text">
          We love A.I. and welcome you to our AI blog. There is so much going on
          in the field of AI and our goal is to keep you up-to-date in
          innovative, informative, and entertaining ways. We see this website as
          a form of digital art as all images and text were generated by
          artificial intelligence (with a little bit of human help). This AI
          blog is written and designed by impressive AIs, and humans merely
          perform copy & paste operations - we showcase the progress of AI
          capabilities on all fronts (text, image, video, audio, design,
          technology, education, etc).
        </p>
        <a href="https://www.artificial-intelligence.blog/">
          <img
            src="https://images.squarespace-cdn.com/content/v1/62ec2bc76a27db7b37a2b32f/524f18a0-75a7-45c8-b55b-b444d244a579/using-hedra-for-ecommerce-product-mockups.jpg"
            alt=""
            className="blog_image"
          />
        </a>
        <a
          href="https://www.artificial-intelligence.blog/"
          className="block_footer"
        >
          E-Commerce Video Mockups with Hedra
        </a>
        <p className="block_footer-text">
          Using Hedra’s generative video AI, we created compelling e-commerce
          video mockups, finding that the technology excels when focusing on
          facial features but struggles with upper or full-body shots, leading
          to less realistic results.
        </p>
      </div>
    </div>
  );
};

export default Homeblog;
